name: Optimize Lineup Daily

#Daily so tomorrow AM I can see if it did it on it's own

on:
  schedule:
    # GitHub cron is UTC. 06:00 UTC ≈ 09:00 Asia/Jerusalem in summer. 
    - cron: '0 8 * * *'
    - cron: '0 */6 * * *'
    - cron: '52 8 * * *'   # 11:52 in summer (UTC+3)
    - cron: '52 9 * * *'   # 11:52 in winter (UTC+2)
    - cron: '20 9 * * *'   # 12:20 Asia/Jerusalem during DST (UTC+3)
    - cron: '20 10 * * *'  # 12:20 Asia/Jerusalem during standard time (UTC+2)
  workflow_dispatch: {}   # lets you run it manually from the Actions tab

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.5"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run optimizer
        env:
          YEAR:       ${{ secrets.YEAR }}
          LEAGUE_ID:  ${{ secrets.LEAGUE_ID }}
          TEAM_ID:    ${{ secrets.TEAM_ID }}
          SWID:       ${{ secrets.SWID }}
          ESPN_S2:    ${{ secrets.ESPN_S2 }}
          # optional SMTP alerting
          SMTP_HOST:  ${{ secrets.SMTP_HOST }}
          SMTP_PORT:  ${{ secrets.SMTP_PORT }}
          SMTP_USER:  ${{ secrets.SMTP_USER }}
          SMTP_PASS:  ${{ secrets.SMTP_PASS }}
          ALERT_TO:   ${{ secrets.ALERT_TO }}
        run: python3 -u main.py
